name: mdigit_span_tasks_ema
description: "mDigitSpanTasksEMA: A mobile application for measuring verbal working memory in real-time."
publish_to: 'none' 

version: 0.1.0

environment:
  sdk: '>=2.18.0-216.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  digit_span_tasks:
    git:
      url: https://github.com/mario-bermonti/digit_span_tasks.git
      ref: d590f8d2f991c19acaf615d36bdd6f8ce966d10d
  cognitive_data:
    git:
      url: https://github.com/mario-bermonti/cognitive_data.git
      ref: 4ba539786a5fd2ee74194b0c34fe03d562ef99ed
  firebase_core: ^2.28.0
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.19.0
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  firebase_auth_mocks: ^0.13.0

flutter:
  uses-material-design: true
