name: mdigit_span_tasks_ema
description: "mDigitSpanTasksEMA: A mobile application for measuring verbal working memory in real-time."
publish_to: 'none' 

version: 0.1.0

environment:
  sdk: '>=2.18.0-216.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  digit_span_tasks:
    git:
      url: https://github.com/mario-bermonti/digit_span_tasks.git
      ref: 84eced4ef1cf03ac23ba7838bc60ba4d04fe7174
  cognitive_data:
    git:
      url: https://github.com/mario-bermonti/cognitive_data.git
      ref: 1edb41fd77d5e8cb6ae2f6d515f33755dbe1c55d
  firebase_core: ^2.28.0
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.19.0
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.8.1
  research_package: ^1.5.0
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  firebase_auth_mocks: ^0.13.0
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/baseline_questions/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"