name: mdigit_span_tasks_ema
description: "mDigitSpanTasksEMA: A mobile application for measuring verbal working memory in real-time."
publish_to: 'none' 

version: 0.1.0

environment:
  sdk: '>=2.18.0-216.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  digit_span_tasks:
    git:
      url: https://github.com/mario-bermonti/digit_span_tasks.git
      ref: v0.2.1
  cognitive_data:
    git:
      url: https://github.com/mario-bermonti/cognitive_data.git
      ref: v0.2.0
  path_provider: ^2.0.15
  permission_handler: ^10.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
