name: Build android app

on: [pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/dependencies
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.19.0
        with:
          channel: stable
          flutter-version: 3.19.4
          cache: true
      - run: flutter doctor --verbose
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
